# Generated by Django 5.2.11 on 2026-04-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='Sin Teléfono', max_length=20),
        ),
    ]
